import type { ProviderType, ApiKeyMode } from '@/types';

export interface ProviderPreset {
  id: string;
  name: string;
  type: ProviderType;
  description: string;
  baseUrl: string;
  apiKeyEnvDefault: string;
  apiKeyMode: ApiKeyMode;
  models: string[];
  supportsModelFetch: boolean;
  supportsReasoning: boolean;
  supportsTools: boolean;
  category: 'cloud' | 'local' | 'meta' | 'custom';
}

export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    type: 'openai',
    description: 'GPT-4o, GPT-4, o1, o3',
    baseUrl: 'https://api.openai.com/v1',
    apiKeyEnvDefault: 'OPENAI_API_KEY',
    apiKeyMode: 'env',
    models: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo', 'gpt-4', 'o1', 'o1-mini', 'o3-mini', 'gpt-3.5-turbo'],
    supportsModelFetch: true,
    supportsReasoning: true,
    supportsTools: true,
    category: 'cloud',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    type: 'openrouter',
    description: 'Access 200+ models via one API',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyEnvDefault: 'OPENROUTER_API_KEY',
    apiKeyMode: 'env',
    models: ['openai/gpt-4o', 'anthropic/claude-opus-4-5', 'anthropic/claude-sonnet-4-5', 'google/gemini-2.0-flash-001', 'meta-llama/llama-3.3-70b-instruct', 'deepseek/deepseek-chat'],
    supportsModelFetch: true,
    supportsReasoning: true,
    supportsTools: true,
    category: 'cloud',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    type: 'anthropic',
    description: 'Claude 4, 3.5 Sonnet, Opus, Haiku',
    baseUrl: 'https://api.anthropic.com/v1',
    apiKeyEnvDefault: 'ANTHROPIC_API_KEY',
    apiKeyMode: 'env',
    models: ['claude-opus-4-5', 'claude-sonnet-4-5', 'claude-3-5-sonnet-20241022', 'claude-3-5-haiku-20241022', 'claude-3-opus-20240229'],
    supportsModelFetch: false,
    supportsReasoning: true,
    supportsTools: true,
    category: 'cloud',
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    type: 'gemini',
    description: 'Gemini 2.5, 2.0, 1.5 Pro/Flash',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    apiKeyEnvDefault: 'GOOGLE_AI_API_KEY',
    apiKeyMode: 'env',
    models: ['gemini-2.5-flash-preview-05-20', 'gemini-2.5-pro-preview-05-06', 'gemini-2.0-flash-001', 'gemini-1.5-pro', 'gemini-1.5-flash'],
    supportsModelFetch: true,
    supportsReasoning: true,
    supportsTools: true,
    category: 'cloud',
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    type: 'azure-openai',
    description: 'OpenAI models on Azure',
    baseUrl: '',
    apiKeyEnvDefault: 'AZURE_OPENAI_API_KEY',
    apiKeyMode: 'env',
    models: ['gpt-4o', 'gpt-4', 'gpt-35-turbo'],
    supportsModelFetch: false,
    supportsReasoning: true,
    supportsTools: true,
    category: 'cloud',
  },
  {
    id: 'openai-compatible',
    name: 'OpenAI Compatible',
    type: 'openai-compatible',
    description: 'Generic OpenAI-compatible endpoint',
    baseUrl: '',
    apiKeyEnvDefault: 'CUSTOM_API_KEY',
    apiKeyMode: 'env',
    models: [],
    supportsModelFetch: true,
    supportsReasoning: false,
    supportsTools: true,
    category: 'custom',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    type: 'openai-compatible',
    description: 'Mistral Large, Medium, Codestral',
    baseUrl: 'https://api.mistral.ai/v1',
    apiKeyEnvDefault: 'MISTRAL_API_KEY',
    apiKeyMode: 'env',
    models: ['mistral-large-latest', 'mistral-medium-latest', 'codestral-latest', 'mistral-small-latest'],
    supportsModelFetch: true,
    supportsReasoning: false,
    supportsTools: true,
    category: 'cloud',
  },
  {
    id: 'groq',
    name: 'Groq',
    type: 'openai-compatible',
    description: 'Ultra-fast inference engine',
    baseUrl: 'https://api.groq.com/openai/v1',
    apiKeyEnvDefault: 'GROQ_API_KEY',
    apiKeyMode: 'env',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768', 'gemma2-9b-it'],
    supportsModelFetch: true,
    supportsReasoning: false,
    supportsTools: true,
    category: 'cloud',
  },
  {
    id: 'together-ai',
    name: 'Together AI',
    type: 'openai-compatible',
    description: 'Open-source model hosting',
    baseUrl: 'https://api.together.xyz/v1',
    apiKeyEnvDefault: 'TOGETHER_API_KEY',
    apiKeyMode: 'env',
    models: ['meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo', 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo', 'mistralai/Mixtral-8x7B-Instruct-v0.1'],
    supportsModelFetch: true,
    supportsReasoning: false,
    supportsTools: true,
    category: 'cloud',
  },
  {
    id: 'fireworks-ai',
    name: 'Fireworks AI',
    type: 'openai-compatible',
    description: 'Fast open-source model inference',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    apiKeyEnvDefault: 'FIREWORKS_API_KEY',
    apiKeyMode: 'env',
    models: ['accounts/fireworks/models/llama-v3p1-70b-instruct', 'accounts/fireworks/models/mixtral-8x7b-instruct'],
    supportsModelFetch: true,
    supportsReasoning: false,
    supportsTools: true,
    category: 'cloud',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    type: 'openai-compatible',
    description: 'DeepSeek-V3, DeepSeek Coder',
    baseUrl: 'https://api.deepseek.com/v1',
    apiKeyEnvDefault: 'DEEPSEEK_API_KEY',
    apiKeyMode: 'env',
    models: ['deepseek-chat', 'deepseek-coder', 'deepseek-reasoner'],
    supportsModelFetch: true,
    supportsReasoning: true,
    supportsTools: true,
    category: 'cloud',
  },
  {
    id: 'moonshot',
    name: 'Moonshot',
    type: 'openai-compatible',
    description: 'Moonshot Kimi models',
    baseUrl: 'https://api.moonshot.cn/v1',
    apiKeyEnvDefault: 'MOONSHOT_API_KEY',
    apiKeyMode: 'env',
    models: ['moonshot-v1-128k', 'moonshot-v1-32k', 'moonshot-v1-8k'],
    supportsModelFetch: true,
    supportsReasoning: false,
    supportsTools: true,
    category: 'cloud',
  },
  {
    id: 'xai',
    name: 'xAI',
    type: 'openai-compatible',
    description: 'Grok models by xAI',
    baseUrl: 'https://api.x.ai/v1',
    apiKeyEnvDefault: 'XAI_API_KEY',
    apiKeyMode: 'env',
    models: ['grok-2', 'grok-2-mini'],
    supportsModelFetch: true,
    supportsReasoning: false,
    supportsTools: true,
    category: 'cloud',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    type: 'openai-compatible',
    description: 'Online LLMs with search',
    baseUrl: 'https://api.perplexity.ai',
    apiKeyEnvDefault: 'PERPLEXITY_API_KEY',
    apiKeyMode: 'env',
    models: ['sonar-pro', 'sonar', 'sonar-reasoning'],
    supportsModelFetch: false,
    supportsReasoning: true,
    supportsTools: false,
    category: 'cloud',
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    type: 'openai-compatible',
    description: 'Wafer-scale inference',
    baseUrl: 'https://api.cerebras.ai/v1',
    apiKeyEnvDefault: 'CEREBRAS_API_KEY',
    apiKeyMode: 'env',
    models: ['llama3.1-8b', 'llama3.1-70b'],
    supportsModelFetch: true,
    supportsReasoning: false,
    supportsTools: false,
    category: 'cloud',
  },
  {
    id: 'ollama',
    name: 'Ollama',
    type: 'ollama',
    description: 'Local models via Ollama',
    baseUrl: 'http://localhost:11434',
    apiKeyEnvDefault: '',
    apiKeyMode: 'none',
    models: ['llama3.2', 'llama3.1', 'codellama', 'mistral', 'qwen2.5-coder', 'deepseek-coder-v2'],
    supportsModelFetch: true,
    supportsReasoning: false,
    supportsTools: true,
    category: 'local',
  },
  {
    id: 'lm-studio',
    name: 'LM Studio',
    type: 'lm-studio',
    description: 'Local models via LM Studio',
    baseUrl: 'http://localhost:1234/v1',
    apiKeyEnvDefault: '',
    apiKeyMode: 'none',
    models: [],
    supportsModelFetch: true,
    supportsReasoning: false,
    supportsTools: false,
    category: 'local',
  },
  {
    id: 'vllm',
    name: 'vLLM',
    type: 'vllm',
    description: 'Self-hosted vLLM server',
    baseUrl: 'http://localhost:8000/v1',
    apiKeyEnvDefault: '',
    apiKeyMode: 'none',
    models: [],
    supportsModelFetch: true,
    supportsReasoning: false,
    supportsTools: false,
    category: 'local',
  },
  {
    id: 'litellm',
    name: 'LiteLLM',
    type: 'litellm',
    description: 'LiteLLM proxy server',
    baseUrl: 'http://localhost:4000',
    apiKeyEnvDefault: 'LITELLM_API_KEY',
    apiKeyMode: 'env',
    models: [],
    supportsModelFetch: true,
    supportsReasoning: false,
    supportsTools: true,
    category: 'local',
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    type: 'opencode',
    description: 'OpenCode AI provider',
    baseUrl: '',
    apiKeyEnvDefault: 'OPENCODE_API_KEY',
    apiKeyMode: 'env',
    models: [],
    supportsModelFetch: false,
    supportsReasoning: false,
    supportsTools: false,
    category: 'meta',
  },
  {
    id: 'zen',
    name: 'Zen',
    type: 'zen',
    description: 'Zen AI provider',
    baseUrl: '',
    apiKeyEnvDefault: 'ZEN_API_KEY',
    apiKeyMode: 'env',
    models: [],
    supportsModelFetch: false,
    supportsReasoning: false,
    supportsTools: false,
    category: 'meta',
  },
  {
    id: '9router',
    name: '9Router',
    type: '9router',
    description: 'Multi-model router (opus-sonnet-gemini)',
    baseUrl: 'https://api.9router.ai/v1',
    apiKeyEnvDefault: 'NINE_ROUTER_API_KEY',
    apiKeyMode: 'env',
    models: ['9router/opus-sonnet-gemini', '9router/auto'],
    supportsModelFetch: true,
    supportsReasoning: true,
    supportsTools: true,
    category: 'cloud',
  },
  {
    id: 'custom',
    name: 'Custom',
    type: 'custom',
    description: 'Custom provider endpoint',
    baseUrl: '',
    apiKeyEnvDefault: '',
    apiKeyMode: 'env',
    models: [],
    supportsModelFetch: true,
    supportsReasoning: false,
    supportsTools: false,
    category: 'custom',
  },
];

export function getPresetById(id: string): ProviderPreset | undefined {
  return PROVIDER_PRESETS.find(p => p.id === id);
}
